spring:
  datasource:
    url: jdbc:h2:mem:appdb
    username: sa
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop # whenever we restart app, it creates and close the app, it drops the table
  h2:
    console:
      enabled: true


# ddl - data definition language (Perform SQL query of creating a table by itself through Hibernate)
#  jdbc:h2:mem:appdb - in memory, will be lost
#  dbc:h2:./app -  database will be there