
server:
  port: 8062

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8051/eureka

spring:
  application:
    name: EMPLOYEEMANAGEMENT
  datasource:
    url: jdbc:h2:./empmandb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true


